[package]
name = "GOL-core-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rand = "0.8.4"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
js-sys="0.3"
web-sys="0.3"


[lib]
crate-type = ["cdylib", "rlib"]
